
def puts_source(base,f)
  puts "## "+f
  puts "```"
  puts open(base+"/"+f).read
  puts "```"
  puts ""
end

puts "# 四択クイズアプリサンプルコード"

base = "androidapp/app/src/main/java/net/lmlab/fourChoiceQuestion"
Dir.entries(base).sort.each do |f|
  next unless f.end_with? ".kt"
  puts_source(base,f)
end

base = "androidapp/app/src/main/res/layout"
Dir.entries(base).sort.each do |f|
  next unless f.end_with? ".xml"
  puts_source(base,f)
end

puts_source("androidapp/app/src/main/res/values","strings.xml")

puts "## その他のリソース"
base = "androidapp/app/src/main/res/drawable"
puts "- res/drawable (画像)"
Dir.entries(base).sort.each do |f|
  next unless f.end_with? ".png"
  puts "  - "+f
end
base = "androidapp/app/src/main/res/raw"
puts "- res/raw (音声)"
Dir.entries(base).sort.each do |f|
  next unless f.end_with? ".mp3"
  puts "  - "+f
end
puts ""

puts "## 生成情報"
puts Time.now.to_s+" "+ `git show -s --format=%H`+"  "
puts "Generated by "+__FILE__
